require "./cream/*"


module Cream
	include ICSGOServers_730
	include ICSGOTournaments_730
	include IDOTA2Fantasy_570
	include IDOTA2MatchStats_570
	include IDOTA2Match_570
	include IDOTA2StreamSystem_570
	include IDOTA2Teams_570
	include IDOTA2Ticket_570
	include IEconDOTA2_570
	include IEconItems_218620
	include IEconItems_221540
	include IEconItems_238460
	include IEconItems_440
	include IEconItems_570
	include IEconItems_620
	include IEconItems_730
	include IEconItems_841
	include IGCVersion_440
	include IGCVersion_570
	include IGCVersion_730
	include IPortal2Leaderboards_620
	include IPortal2Leaderboards_841
	include ISteamApps
	include ISteamBitPay
	include ISteamCDN
	include ISteamDirectory
	include ISteamEconomy
	include ISteamEnvoy
	include ISteamNews
	include ISteamPayPalPaymentsHub
	include ISteamRemoteStorage
	include ISteamUser
	include ISteamUserAuth
	include ISteamUserOAuth
	include ISteamUserStats
	include ISteamWebAPIUtil
	include ISteamWebUserPresenceOAuth
	include ITFItems_440
	include ITFPromos_440
	include ITFPromos_570
	include ITFPromos_620
	include ITFPromos_841
	include ITFSystem_440
	include IGameServersService
	include IPublishedFileService
	include IPlayerService
	include IInventoryService
	include IEconService
	include ICheatReportingService
	include IAccountRecoveryService
end