require "./cream/*"


module Cream
	include ICSGOServers
	include ICSGOTournaments
	include IDOTA2Fantasy
	include IDOTA2MatchStats
	include IDOTA2Match
	include IDOTA2StreamSystem
	include IDOTA2Teams
	include IDOTA2Ticket
	include IEconDOTA2
	include IEconItems
	include IEconItems
	include IEconItems
	include IEconItems
	include IEconItems
	include IEconItems
	include IEconItems
	include IEconItems
	include IGCVersion
	include IGCVersion
	include IGCVersion
	include IPortal2Leaderboards
	include IPortal2Leaderboards
	include ISteamApps
	include ISteamBitPay
	include ISteamCDN
	include ISteamDirectory
	include ISteamEconomy
	include ISteamEnvoy
	include ISteamNews
	include ISteamPayPalPaymentsHub
	include ISteamRemoteStorage
	include ISteamUser
	include ISteamUserAuth
	include ISteamUserOAuth
	include ISteamUserStats
	include ISteamWebAPIUtil
	include ISteamWebUserPresenceOAuth
	include ITFItems
	include ITFPromos
	include ITFPromos
	include ITFPromos
	include ITFPromos
	include ITFSystem
	include IGameServersService
	include IPublishedFileService
	include IPlayerService
	include IInventoryService
	include IEconService
	include ICheatReportingService
	include IAccountRecoveryService
end
